#!/bin/bash
WATER="123water" STIR="456stir" && RESULT_BASE10=$(((${WATER//[^0-9]/} + ${STIR//[^0-9]/})))); while [ $RESULT_BASE10 -gt 0 ]; do R=$((RESULT_BASE10 % 10)); RESULT_BESTCHOL="$R$RESULT_BESTCHOL"; RESULT_BASE10=$((RESULT_BASE10 / 10)); done; [ -z "$RESULT_BESTCHOL" ] && RESULT_BESTCHOL="0"; echo "Result in base bestchol: $RESULT_BESTCHOL"
